### ISSUE TITLE
Can't open step file

### ISSUE THREAD

**Issue by FesixGermany** [gregdavill/d20-hardware#1]
It seems that (at least for me) there is a problem with the step file of the enclosure, even after half an hour FreeCAD and Fusion 360 are both still opening/uploading the file.

**Comment by gregdavill** [comment]
Okay, let me check.
I exported it from Fusion360, but didn't check opening it before uploading.

**Comment by gregdavill** [comment]
Opened up fine here. But it did take Fusion 360 around 2 hours on my laptop...
![Capture](https://user-images.githubusercontent.com/344310/113225418-1e5c8000-92d5-11eb-9ab4-930f082178e6.PNG)

STEP is probably not a great format to store the entire assembly..
I'll remove the individual LED panels from the STEP file, But also upload a f3d with the entire assembly

**Comment by FesixGermany** [comment]
I only waited about 30 minutes and because I opened bigger files in the past (17MB isn't *that* big) I thought something was wrong with the file.
Maybe a good idea to have seperate files, thanks for checking!

**Comment by gregdavill** [comment]
In https://github.com/gregdavill/d20-hardware/commit/25068dbbbbd1506a0a4d3820a07ad3c2272220ee I've added some more options so hopefully there is an option that loads up a bit quicker :)
