### ISSUE TITLE
Enclosure walls reported to be too thin for 3D printing

### ISSUE THREAD

**Issue by akay** [gregdavill/d20-hardware#4]
I just tried to get the enclosures printed by JLCPCB, as I don't have a printer. I uploaded both `.stl` files and using `PA12-HP Nylon` as the material, sent them for inspection before printing and they got back to me a few hours later:

> As shown below, the wall thickness of the indicated red area is not enough which has a high risk of deformation, crack and loss, will this risk be acceptable for you? Yes or NO??
> 
> If not, could you please kindly increase it to be at least 1mm to proceed?
> 
> It would be much better if the thickness of the whole model can be increased into 2mm.
>
>![image](https://user-images.githubusercontent.com/5215129/154084306-c918d6a2-7230-458c-b3fe-6518635fc195.png)
>![image](https://user-images.githubusercontent.com/5215129/154084366-d9ee9be2-6dea-48f3-a9de-7de4e3a19b56.png)
>![image](https://user-images.githubusercontent.com/5215129/154084421-0ddbd943-dd6b-48f8-963c-0f62afc2e5b2.png)

In hindsight, they do specify the requirements for 3D printing below the upload button:
![image](https://user-images.githubusercontent.com/5215129/154085030-59b1f997-d70b-4058-8e54-f801c948c862.png)

Not being familiar with 3D printing (but willing to learn!), and on the off-chance someone else runs into the same issue, I wanted to ask you what steps should be taken at this point, if any.

**Comment by gregdavill** [comment]
I feel like some pretty major modifications would need to be made to fulfill these requirements.

The model was designed to be printed with shapeways, which accepted the file without issue. 

I also managed to print this with PCBWay's service, also using Nylon PA12. 
But the tolerance on the lid was a bit off compared to shapeways, I think they angled the part differently when printing.

**Comment by gregdavill** [comment]
Some more insight, out of the two parts I got from PCBWay, one had a chip along one of the edges. The print would still technically work.

This is basically what they're asking in the first place. That due to the geometry some features might break/crack. This also depends on how rough they are with their internal process and shipping conditions. 

You should be able to agree, and have them still build it for you.

**Comment by akay** [comment]
Just checked Shapeways pricing for printing both and shipping them to Europe, and I think it will be worth it to take a chance and get it printed by PCBWay or JLCPCB 😂

Thank you!

**Comment by gregdavill** [comment]
Totally understand! When I'd originally designed this these lower cost services didn't exist yet in their current form. 

I'd be very interested to see what your experience is if you order these. I'll be writing up a review of the PCBWay prints, would be nice to include a comparison.

**Comment by akay** [comment]
I will definitely let you know when I receive them!

**Comment by epac-tom** [comment]
@akay did you go ahead and order these? How did they turn out?
