### ISSUE TITLE
JLCPCB controller printing issue

### ISSUE THREAD

**Issue by akay** [gregdavill/d20-hardware#5]
I uploaded the controller zip file to PCB to be printed, and they just got back to me with this:

> Sorry to bother you, but there is an issue that we want to confirm with you before proceeding.
> 
> As shown below, comparing the drill diameter the drawing chart, it seems that the holes on the drill layer have been compensated, is the file used for production before? Please help to confirm A or B?
> 
> A:If the file is production file, we fabricate as per this gerber without further compensation and optimization
> 
> B: If the gerber is original file, that means we will add +0.05 for NPTH and +0.15 for PTH, + 0.015mm trace width when we making production file..(Making clearance for the data of gerber file )
> ![image](https://user-images.githubusercontent.com/5215129/154801436-0101ed75-aa7d-405c-b0af-6510b18ce46c.png)

I'm not sure I understand the question, but I think they are asking whether this file has been printed before without problems, in which case I should be replying with `A`. What do you think?

I'm creating the issue in case anyone else experiences the same confusion in the future.

**Comment by gregdavill** [comment]
I'm not sure exactly why JLC asks this, surely they should know if the file has been run through their DFM optimization before.

The design gerbers are straight out of KiCad, so you should typically go for option 'B'. 
But I've found asking for option 'A' is also fine most of the time.

**Comment by akay** [comment]
Thank you! I responded with 'B', and will update this issue if there are any issues with the controller during assembly :)
